name: Go checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.9.6
      - name: Run Staticcheck
        run: |
          staticcheck -f stylish ./...
      - name: Run Gosec
        run: |
          gosec -verbose text ./...
  run-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          wget https://github.com/securego/gosec/releases/download/v2.9.6/gosec_2.9.6_windows_amd64.tar.gz -o gosec.tar.gz
          tar -xvf gosec_2.9.6_windows_amd64.tar.gz
      - name: Run Staticcheck
        run: |
          staticcheck -f stylish ./...
      - name: Run Gosec
        run: |
          ./gosec.exe -verbose text ./...
